name: aroma_journey
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.4
  firebase_auth: ^4.8.0
  flutter_modular: ^6.1.0+1
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  json_annotation: ^4.8.1
  cloud_firestore: ^4.9.0
  bloc: ^8.1.2
  smooth_page_indicator: ^1.1.0
  provider: ^6.0.5
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  auto_size_text: ^3.0.0
  from_css_color: ^2.0.0
  intl: ^0.18.1
  json_path: ^0.6.2
  timeago: ^3.5.0
  url_launcher: ^6.1.12
  flutter_animate: ^4.2.0+1
  page_transition: ^2.0.9
  shared_preferences: ^2.2.0
  go_router: ^10.1.0
  flutter_svg: ^2.0.7
  asuka: ^2.2.0
  cached_network_image: ^3.2.3
  badges: ^3.1.1
  chips_choice: ^3.0.0
  logging: ^1.2.0
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/