// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-cbdkMHIePHIKeJfQH4IRVZMQTCddW0',
    appId: '1:167171721391:web:990d0f904cdb73f8e46c5a',
    messagingSenderId: '167171721391',
    projectId: 'aroma-journey-8f041',
    authDomain: 'aroma-journey-8f041.firebaseapp.com',
    storageBucket: 'aroma-journey-8f041.appspot.com',
    measurementId: 'G-82RXXC0QKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqPwK-vDHh7VTncWalLyQLcM6RLTl3JkU',
    appId: '1:167171721391:android:c2b3adf5b11cc305e46c5a',
    messagingSenderId: '167171721391',
    projectId: 'aroma-journey-8f041',
    storageBucket: 'aroma-journey-8f041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd4xow242Df97ixJy8_X_TW3kBp3_4gDw',
    appId: '1:167171721391:ios:1d6d3b47d23634eee46c5a',
    messagingSenderId: '167171721391',
    projectId: 'aroma-journey-8f041',
    storageBucket: 'aroma-journey-8f041.appspot.com',
    iosClientId: '167171721391-c1rb66bjdqav4m65qckr6ikq6e3a5b91.apps.googleusercontent.com',
    iosBundleId: 'net.bwnyasse.aromaJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd4xow242Df97ixJy8_X_TW3kBp3_4gDw',
    appId: '1:167171721391:ios:1d6d3b47d23634eee46c5a',
    messagingSenderId: '167171721391',
    projectId: 'aroma-journey-8f041',
    storageBucket: 'aroma-journey-8f041.appspot.com',
    iosClientId: '167171721391-c1rb66bjdqav4m65qckr6ikq6e3a5b91.apps.googleusercontent.com',
    iosBundleId: 'net.bwnyasse.aromaJourney',
  );
}
